dist: trusty
sudo: required
language: node_js
node_js:
  - "v8.3.0"
os:
  - linux
env:
  global:
    - DBUS_SESSION_BUS_ADDRESS=/dev/null
    - DISPLAY=:99.0
    - CHROME_BIN=chromium-browser
before_script:
  - sh -e /etc/init.d/xvfb start
install:
  - npm install
  - webdriver-manager update
script:
  - npm run lint
  - npm run test
  - npm run e2e
